# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.CharField(max_length=32),
        ),
    ]
