# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180204_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Classes'),
        ),
    ]
