# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180204_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Classes_related', to='app01.Classes'),
        ),
    ]
