# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20180205_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='cls',
            new_name='t2c',
        ),
    ]
